"""create initial tables

Revision ID: 0d7772ba8bd1
Revises: f4e7bf8314e5
Create Date: 2026-03-02 16:26:26.272034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7772ba8bd1'
down_revision: Union[str, Sequence[str], None] = 'f4e7bf8314e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('limite_contas', sa.Integer(), nullable=True),
    sa.Column('limite_pastos', sa.Integer(), nullable=True),
    sa.Column('limite_vendas', sa.Integer(), nullable=True),
    sa.Column('limite_compras', sa.Integer(), nullable=True),
    sa.Column('limite_despesas', sa.Integer(), nullable=True),
    sa.Column('limite_movimentacoes', sa.Integer(), nullable=True),
    sa.Column('relatorio_resumo', sa.Boolean(), nullable=False),
    sa.Column('relatorio_por_pasto', sa.Boolean(), nullable=False),
    sa.Column('relatorio_fluxo_caixa', sa.Boolean(), nullable=False),
    sa.Column('relatorio_dre', sa.Boolean(), nullable=False),
    sa.Column('relatorio_evolucao_patrimonio', sa.Boolean(), nullable=False),
    sa.Column('relatorio_resultado_mensal', sa.Boolean(), nullable=False),
    sa.Column('relatorio_giro_animais', sa.Boolean(), nullable=False),
    sa.Column('relatorio_ranking_pastos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contas_bancarias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tamanho_ha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_pastagem', sa.Enum('BRACHIARIA', 'MOMBACA', 'TANZANIA', name='tipopastagem'), nullable=False),
    sa.Column('capacidade_sugerida', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('pasto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['pasto_id'], ['pastos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pasto_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['pasto_id'], ['pastos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_financeiras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_gado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('pasto_origem_id', sa.Integer(), nullable=False),
    sa.Column('pasto_destino_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pasto_destino_id'], ['pastos.id'], ),
    sa.ForeignKeyConstraint(['pasto_origem_id'], ['pastos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('pasto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('lucro_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_bancarias.id'], ),
    sa.ForeignKeyConstraint(['pasto_id'], ['pastos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('movimentacoes_gado')
    op.drop_table('movimentacoes_financeiras')
    op.drop_table('despesas')
    op.drop_table('compras')
    op.drop_table('pastos')
    op.drop_table('contas_bancarias')
    op.drop_table('usuarios')
    op.drop_table('planos')
    # ### end Alembic commands ###
