"""remover  campo transacao_id e add compra_id, venda_id e despesa_id na  movimentacao_financeira

Revision ID: 6771ad0e5bf1
Revises: f5ebb84fa81d
Create Date: 2026-06-10 20:53:44.379218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6771ad0e5bf1'
down_revision: Union[str, Sequence[str], None] = 'f5ebb84fa81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_financeiras', sa.Column('compra_id', sa.Integer(), nullable=True))
    op.add_column('movimentacoes_financeiras', sa.Column('venda_id', sa.Integer(), nullable=True))
    op.add_column('movimentacoes_financeiras', sa.Column('despesa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimentacoes_financeiras', 'compras', ['compra_id'], ['id'])
    op.create_foreign_key(None, 'movimentacoes_financeiras', 'despesas', ['despesa_id'], ['id'])
    op.create_foreign_key(None, 'movimentacoes_financeiras', 'vendas', ['venda_id'], ['id'])
    op.drop_column('movimentacoes_financeiras', 'transacao_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_financeiras', sa.Column('transacao_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimentacoes_financeiras', type_='foreignkey')
    op.drop_constraint(None, 'movimentacoes_financeiras', type_='foreignkey')
    op.drop_constraint(None, 'movimentacoes_financeiras', type_='foreignkey')
    op.drop_column('movimentacoes_financeiras', 'despesa_id')
    op.drop_column('movimentacoes_financeiras', 'venda_id')
    op.drop_column('movimentacoes_financeiras', 'compra_id')
    # ### end Alembic commands ###
