"""add campo transacao_id movimentacao_financeira

Revision ID: f5ebb84fa81d
Revises: 0d7772ba8bd1
Create Date: 2026-06-02 22:05:59.098267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5ebb84fa81d'
down_revision: Union[str, Sequence[str], None] = '0d7772ba8bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_financeiras', sa.Column('transacao_id', sa.Integer(), nullable=True))
    op.alter_column('movimentacoes_gado', 'custo_unitario',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimentacoes_gado', 'custo_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('movimentacoes_financeiras', 'transacao_id')
    # ### end Alembic commands ###
